# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170806_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='inherits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_permissions', to='login.Permission'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='login.Team', verbose_name='Equipe lié'),
        ),
    ]
